import {categories,esc,safeUrl,sourceName,normalize,filterEvents,dayKey,time,headline,displayText,pageEvents,groupMapReports,locationHistory} from './desk-model.mjs';
const $=id=>document.getElementById(id);
const dataRoot='/data/signal-desk/';
let current=window.retainedSnapshot,events=[],selected=null,category='All',map,countryBounds,viewMode='south',visibleLimit=12;
const layers={},markers=new Map();
const colors={Strikes:'#a74232',Clashes:'#bc7635',Security:'#567361',Politics:'#687681',Displacement:'#9c804a',Other:'#74786d'};
function notice(message){$('notice').hidden=!message;$('notice').textContent=message}
async function json(path){const r=await fetch(dataRoot+path,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Request failed '+r.status);return r.json()}
function home(){viewMode='south';map?.fitBounds([[33.035,35.09],[33.49,35.91]],{padding:[30,40],animate:false})}
function control(label,fn){const c=L.control({position:'topleft'});c.onAdd=()=>{const b=L.DomUtil.create('button','map-home');b.textContent=label;b.type='button';b.onclick=fn;L.DomEvent.disableClickPropagation(b);return b};c.addTo(map)}
function setupMap(){
 if(!window.L){notice('The map could not load. You can still read and search every update.');return}
 map=L.map('map',{zoomSnap:.25,zoomDelta:.5,scrollWheelZoom:false,minZoom:7,maxZoom:14,maxBounds:[[32.65,34.5],[34.85,36.85]],maxBoundsViscosity:.78});
 const legend=document.createElement('div');legend.className='map-legend';legend.setAttribute('aria-label','Map legend');legend.innerHTML=['Strikes','Clashes','Security','Other'].map(c=>'<span><i style="background:'+colors[c]+'"></i>'+c+'</span>').join('')+'<span><b class="line yellow"></b> Yellow line · observed 8 Sept</span><span><b class="line"></b> Lebanese border</span>';$('map').parentElement.append(legend);
 for(const [name,z] of [['boundaries',390],['yellowLine',395]]){map.createPane(name);map.getPane(name).style.zIndex=z;map.getPane(name).style.pointerEvents='none'}
 layers.events=L.layerGroup().addTo(map);layers.boundary=L.layerGroup().addTo(map);layers.yellow=L.layerGroup().addTo(map);layers.towns=L.layerGroup().addTo(map);
 const imagery=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:14,attribution:'Imagery &copy; Esri, Maxar, Earthstar Geographics'});
 const relief=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:13,maxZoom:14,opacity:.78,attribution:'Relief &copy; Esri, USGS, NOAA'});
 layers.terrain=L.layerGroup([imagery,relief]).addTo(map);
 home();map.on('dragstart',()=>{viewMode='manual'});map.on('zoomstart',event=>{if(event.originalEvent)viewMode='manual'});control('Reset view',()=>{$('view-select').value='south';home()});L.control.scale({imperial:false,position:'bottomright'}).addTo(map);
 json('lebanon-boundary.geojson').then(data=>{countryBounds=L.geoJSON(data).getBounds();for(const style of [{color:'#fff9e9',weight:4.5,opacity:.9,fill:false},{color:'#344b48',weight:1.8,opacity:1,fill:false}])L.geoJSON(data,{pane:'boundaries',interactive:false,smoothFactor:0,style}).addTo(layers.boundary)}).catch(()=>notice('The Lebanese border layer is unavailable. Retrying on the next page load.'));
 json('yellow-line-liveuamap.geojson').then(data=>{for(const style of [{color:'#725c24',weight:4.8,opacity:.85,lineCap:'round'},{color:'#ffda43',weight:2.8,opacity:1,lineCap:'round'}])L.geoJSON(data,{pane:'yellowLine',interactive:false,smoothFactor:0,style}).addTo(layers.yellow)}).catch(()=>notice('The yellow line could not load. The saved geometry has not been changed.'));
 [['Tyre',33.271,35.204],['Nabatieh',33.378,35.484],['Bint Jbeil',33.12,35.433],['Beirut',33.89,35.5],['Tripoli',34.436,35.849],['Baalbek',34.006,36.208],['LEBANON',33.44,35.35],['ISRAEL',33.025,35.45],['SYRIA',33.49,35.95]].forEach(([name,lat,lng])=>L.tooltip({permanent:true,direction:'center',className:'place-label'+(name===name.toUpperCase()?' country-label':''),opacity:1}).setLatLng([lat,lng]).setContent(name).addTo(layers.towns));
 document.querySelectorAll('[data-layer]').forEach(input=>input.addEventListener('change',()=>input.checked?map.addLayer(layers[input.dataset.layer]):map.removeLayer(layers[input.dataset.layer])));
 let previousWidth=$('map').clientWidth;
 new ResizeObserver(()=>{const width=$('map').clientWidth;map.invalidateSize();if(Math.abs(width-previousWidth)>10){previousWidth=width;if(viewMode==='south')home();else if(viewMode==='country'&&countryBounds)map.fitBounds(countryBounds,{padding:[30,40],animate:false})}}).observe($('map'));
}
function drawMarkers(list){
 if(!map)return;layers.events.clearLayers();markers.clear();
 groupMapReports(list).forEach(group=>{const e=group.latest,active=group.reports.some(report=>report.id===selected);const m=L.circleMarker([group.lat,group.lng],{radius:active?7:4.5,fillColor:colors[e.displayCategory],color:'#fff9ee',fillOpacity:1,weight:2.8,className:'event-dot'+(active?' active':'')}).addTo(layers.events);
 m.bindTooltip('<time>Latest: '+esc(time(e.timestamp,true))+' · Beirut</time><p>'+esc(headline(e))+'</p><small>'+group.reports.length+' report'+(group.reports.length===1?'':'s')+' at this location</small>',{direction:'auto',className:'event-tip',offset:[8,0]});m.on('click',()=>choose(e.id,false));
 const el=m.getElement();el?.setAttribute('tabindex','0');el?.setAttribute('role','button');el?.setAttribute('aria-label',time(e.timestamp)+': '+e.title);el?.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose(e.id,false)}});el?.addEventListener('focus',()=>m.openTooltip());el?.addEventListener('blur',()=>m.closeTooltip());
 markers.set(group.key,{marker:m,ids:group.reports.map(report=>report.id)});
 });
}
function renderDetail(e){
 if(!e){$('detail').innerHTML='<div class="detail-placeholder"><span class="eyebrow">In focus</span><h2>Select an update</h2><p>Choose a point on the map or a report from the latest updates.</p></div>';return}
 const url=safeUrl(e.source),summary=displayText(e.summary||e.full_text||e.title);
 $('detail').innerHTML='<div class="detail-top"><time>'+esc(time(e.timestamp))+'</time><button id="close-detail" aria-label="Close selected report">×</button></div><h2 dir="auto">'+esc(headline(e))+'</h2><p class="location">⌖ '+esc(e.location||'Lebanon')+' <span class="detail-tag">'+esc(e.displayCategory)+'</span></p><p class="summary" dir="auto">'+esc(summary)+'</p><dl class="detail-facts"><dt>Source</dt><dd>'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(sourceName(e))+' ↗</a>':esc(sourceName(e)))+'</dd><dt>Reported</dt><dd>'+esc(time(e.timestamp,true))+' · Beirut</dd><dt>Location</dt><dd>'+esc(e.location||'Not specified')+'</dd><dt>Category</dt><dd>'+esc(e.displayCategory)+'</dd></dl><div class="detail-actions">'+(e.mapPoints.length?'<button id="view-map" type="button">⌖ View on map</button>':'')+'</div><div class="source"><small>'+(e.mapPoints.length?(/town|approx/i.test(e.geographicPrecision||e.locationPrecision||'')?'Approximate town-level location.':'Mapped location from the collected report.'):'This report has no mapped location yet.')+' Publication time shown where event time is unavailable.</small></div>';
 $('close-detail').addEventListener('click',()=>{selected=null;render()});
 const history=locationHistory(events,e);
 if(history.length>1){const label=document.createElement('label');label.className='location-history';label.textContent='Reports at this location ('+history.length+')';const select=document.createElement('select');select.id='location-history';select.setAttribute('aria-label','Reports at this location');select.style.cssText='display:block;width:100%;max-width:100%;margin:8px 0 12px';for(const report of history){const option=document.createElement('option');option.value=report.id;option.textContent=time(report.timestamp,true)+' · '+headline(report);option.selected=report.id===e.id;select.append(option)}label.append(select);$('detail').querySelector('.detail-actions').before(label);select.addEventListener('change',()=>choose(select.value,false))}
 $('view-map')?.addEventListener('click',()=>{locate(e);$('map').scrollIntoView({block:'center',behavior:'smooth'})});
}
function locate(e){const p=e.mapPoints[0];if(!p||!map)return;viewMode='manual';map.flyTo([p.lat,p.lng],Math.max(map.getZoom(),10.5),{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:.3})}
function choose(id,move=true){selected=id;const index=filterEvents(events,{query:$('query').value,category,date:$('date').value}).findIndex(e=>e.id===id);if(index>=visibleLimit){visibleLimit=Math.ceil((index+1)/12)*12;render()}const e=events.find(e=>e.id===id);renderDetail(e);document.querySelectorAll('.card').forEach(el=>{el.classList.toggle('active',el.dataset.id===id);el.querySelector('button').setAttribute('aria-pressed',String(el.dataset.id===id));if(el.dataset.id===id){const rail=$('cards');rail.scrollTop=el.offsetTop-rail.offsetTop}});markers.forEach(({marker,ids})=>{const active=ids.includes(id);marker.setRadius(active?7:4.5);marker.getElement()?.classList.toggle('active',active)});if(move&&e)locate(e)}
function render(){
 const list=filterEvents(events,{query:$('query').value,category,date:$('date').value});
 if(!list.some(e=>e.id===selected)){selected=null;renderDetail(null)}
 $('visible-count').textContent=list.length+' reports';
 $('cards').innerHTML=list.length?pageEvents(list,visibleLimit).map(e=>'<article class="card '+(e.id===selected?'active':'')+'" data-id="'+esc(e.id)+'"><button type="button" aria-pressed="'+(e.id===selected)+'"><time class="card-clock">'+esc(time(e.timestamp))+'</time><i class="incident-dot" style="background:'+colors[e.displayCategory]+'"></i><span class="card-copy"><span class="card-place">'+esc(e.location||'Lebanon')+'</span><strong dir="auto">'+esc(headline(e))+'</strong></span><span class="card-arrow" aria-hidden="true">›</span></button></article>').join(''):'<p class="empty">No updates match these filters. Try another date, category or search.</p>';
 $('load-more').hidden=visibleLimit>=list.length;$('load-more').textContent='Load more updates ↓ ('+Math.min(visibleLimit,list.length)+' of '+list.length+')';
 $('cards').querySelectorAll('.card button').forEach(b=>b.addEventListener('click',()=>choose(b.closest('.card').dataset.id)));
 drawMarkers(list);const mapped=list.filter(e=>e.mapPoints.length),latest=mapped.length?Math.max(...mapped.map(e=>e.timestamp)):null;$('map-note').textContent=mapped.length+' mapped reports · '+groupMapReports(list).length+' locations · '+(list.length-mapped.length)+' without a mapped location'+(latest?' · Latest mapped: '+time(latest,true)+' Beirut':'');
 document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));
}
function updateFeed(next){current=next;events=next.events.map(normalize).sort((a,b)=>b.timestamp-a.timestamp);const date=$('date').value;$('date').innerHTML='<option value="">All dates</option>'+[...new Set(events.map(e=>dayKey(e.timestamp)))].sort().reverse().map(d=>'<option value="'+d+'">'+d+'</option>').join('');$('date').value=date;
 const today=dayKey(Date.now()/1000);$('count').textContent=events.filter(e=>dayKey(e.timestamp)===today).length+' updates today · '+events.length+' retained';$('updated').textContent='Feed updated '+time(Date.parse(next.generatedAt)/1000);render();if(selected)renderDetail(events.find(e=>e.id===selected));
}
async function status(){try{const data=await json('source-status.json');const list=data.sources||[];const n=data.summary||{};$('source-summary').textContent=' · '+(n.succeeded??list.filter(s=>s.status==='success').length)+'/'+(n.configured??list.length)+' reached · '+['news','telegram','x'].map(p=>{const group=list.filter(s=>s.platform===p);return (p==='x'?'X':p==='news'?'News':'Telegram')+' '+group.filter(s=>s.status==='success').length+'/'+group.length}).join(' · ');$('source-list').innerHTML='<p>Last checked '+esc(time(Date.parse(data.checkedAt)/1000,true))+' · Beirut</p>'+list.map(s=>'<div class="source-row"><strong>'+esc(s.name)+' · '+esc(s.platform)+'</strong><span>'+esc(s.status)+(s.windowComplete===false?' · partial history':'')+' · '+(Number(s.eligible)||0)+' eligible · '+(Number(s.added)||0)+' added</span>'+(s.coverage?'<span>'+esc(s.coverage)+(s.pages?' · '+Number(s.pages)+' pages':'')+'</span>':'')+'<span>Checked '+esc(time(Date.parse(s.checkedAt||data.checkedAt)/1000))+'</span>'+(s.lastSuccessAt?'<span>Last successful read '+esc(time(Date.parse(s.lastSuccessAt)/1000))+'</span>':'')+(s.error?'<span>'+esc(s.error)+'</span>':'')+'</div>').join('')}catch{$('source-summary').textContent=' · unavailable';$('source-list').textContent='Source checks are unavailable. The retained feed is still readable.'}}
async function start(){
 $('current-date').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Beirut',dateStyle:'long'}).format(new Date());
 $('category-select').innerHTML=categories.map(c=>'<option value="'+c+'">'+(c==='All'?'All categories':c)+'</option>').join('');$('category-select').addEventListener('change',()=>{category=$('category-select').value;visibleLimit=12;render()});
 const refilter=()=>{visibleLimit=12;render()};$('query').addEventListener('input',refilter);$('date').addEventListener('change',refilter);$('reset').addEventListener('click',()=>{category='All';$('category-select').value='All';$('query').value='';$('date').value='';selected=null;visibleLimit=12;renderDetail(null);render()});
 $('load-more').addEventListener('click',()=>{visibleLimit+=12;render()});
 $('view-select').addEventListener('change',()=>{if(!map)return;if($('view-select').value==='south')home();else{viewMode='country';map.fitBounds(countryBounds||[[33.05,35.1],[34.7,36.63]],{padding:[30,40]})}});
 $('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else{await Promise.race([document.documentElement.requestFullscreen(),new Promise((_,reject)=>setTimeout(()=>reject(Error('Fullscreen timed out')),2000))])}}catch{notice('Fullscreen is unavailable in this browser. Expand the preview panel instead.')}});
 document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Open map workspace fullscreen');map?.invalidateSize()});
 document.querySelector('.read-analysis').addEventListener('click',()=>{$('full-analysis').open=true});
 setupMap();try{const next=await json('live-social.json');if(Array.isArray(next.events))current=next}catch{notice('Showing the retained news snapshot. The latest feed could not be reached.')}
 updateFeed(current);if(events.length)choose(events[0].id,false);status();setInterval(async()=>{try{const next=await json('live-social.json');if(Array.isArray(next.events)&&Date.parse(next.generatedAt)>Date.parse(current.generatedAt)){updateFeed(next);notice('')}}catch{notice('The latest feed could not be reached. Your current updates remain available.')}status()},60000);
}
start();
